
development:
  adapter: postgresql
  encoding: unicode
  database: hours_of_happiness_development

test:
  adapter: postgresql
  encoding: unicode
  database: hours_of_happiness_test

production:
  adapter: postgresql
  encoding: unicode
  database: hours_of_happiness_production
